# Lecture 6

In [9]:
import numpy as np

x = torch.tensor(np.array([1.0]))
x.requires_grad = True
y = 3 - 2*x**2 + x**4
y.backward()
x.grad.data

tensor([0.], dtype=torch.float64)

In [16]:
import numpy as np

x = torch.tensor(np.array([[1.0], [1.0]]))
A = torch.tensor(np.array([[2.0, -1.0],[1.0, 3.0]]))
x.requires_grad = True

y = torch.mm(torch.mm(torch.transpose(x,0,1), A), x)
y.backward()
x.grad.data

tensor([[4.],
        [6.]], dtype=torch.float64)

In [17]:
import numpy as np

x = torch.tensor(np.array([[1.0, 1.0], [1.0, 1.0]]))
u = torch.tensor(np.array([[1.0],[-1.0]]))
v = torch.tensor(np.array([[1.0],[2.0]]))
x.requires_grad = True

y = torch.mm(torch.mm(torch.transpose(u,1,0),x),v)
y.backward()
x.grad.data

tensor([[ 1.,  2.],
        [-1., -2.]], dtype=torch.float64)