In [5]:
import torchvision.models as models
import torchvision.transforms as transforms
import torch.nn.functional as F
import torch
import os
from PIL import Image
import matplotlib.pyplot as plt

model = models.resnet18(pretrained=True)


In [78]:
model.eval()
mr_shout = Image.open('cdHjrlTW.jpeg')

lr = 0.01
data = transforms.Compose([transforms.Resize(size=224), transforms.CenterCrop(224), transforms.ToTensor()])(mr_shout).unsqueeze(dim=0)

while True:
    data.requires_grad = True
    output = model(data)
    pred = output.argmax(dim = 1)
    print (pred)
    if pred == 229:
        break
    output[:,229].backward()
    temp_data = (data + lr*data.grad).data
    mask = 1- (temp_data > 1)
    mask_grad = torch.mul(data.grad.float(), mask.float())
    data.data += lr*mask_grad

img = data.squeeze().detach().numpy().swapaxes(0,2).swapaxes(1,0)
img = Image.fromarray((img* 255).astype('uint8'), 'RGB')
img.show()

tensor([443])
tensor([443])
tensor([549])
tensor([549])
tensor([921])
tensor([921])
tensor([921])
tensor([921])
tensor([405])
tensor([405])
tensor([405])
tensor([405])
tensor([229])
